##Mini-Boothcamp Numpy Ödevi - Efe Uslu

In [4]:
import numpy as np

In [ ]:
#1. 1'den 10'a kadar bir Numpy dizisi oluşturun
a=np.array(range(1,11))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#2. 2 boyutlu bir Numpy dizisi oluşturun
b=np.random.randint(1,20,size=(9))
b=b.reshape(3,3)
b

array([[ 4, 18,  2],
       [10,  6, 12],
       [ 2, 13,  4]])

In [ ]:
#3. Boyutları 2x3 olan bir Numpy dizisinin satır sayısını bulun
c=np.random.randint(1,10,size=(6))
c=c.reshape(2,3)
rows = c.shape[0]
print("Dizimiz: ")
print(c)
print("Satır Sayısı: ", rows)

Dizimiz: 
[[2 4 9]
 [3 4 3]]
Satır Sayısı:  2


In [ ]:
#4. Boyutları 2x3 olan bir Numpy dizisinin sütun sayısını bulun
lines = c.shape[1]
print("Sütun sayısı: ", lines)

Sütun sayısı:  3


In [ ]:
#4. Bir Numpy dizisindeki en büyük değeri bulun

print(c.max())


9


In [48]:
#6. Bir Numpy dizisindeki en küçük değeri bulun

d=np.random.normal(1,100,20)
print("Dizimiz: ",d)
print()
print("Dizinin minimum değeri: ", d.min())

Dizimiz:  [  96.16774526  -15.21650631   22.70135604  113.55202944  -69.62850452
  -16.97413795  -93.43450606  -36.68228207  133.05145163 -228.24243699
  -51.86849265  128.85573756  125.13374129  186.82404409  -29.76394989
  132.69391175   49.17961312    1.74189147  -73.19387651   89.2589421 ]

Dizinin minimum değeri:  -228.24243699144046


In [49]:
#7. Bir Numpy dizisindeki ortalamayı bulun
print("Dizimiz: ",d)
print()
print("Dizinin ortalama değeri: ", d.mean())



Dizimiz:  [  96.16774526  -15.21650631   22.70135604  113.55202944  -69.62850452
  -16.97413795  -93.43450606  -36.68228207  133.05145163 -228.24243699
  -51.86849265  128.85573756  125.13374129  186.82404409  -29.76394989
  132.69391175   49.17961312    1.74189147  -73.19387651   89.2589421 ]

Dizinin ortalama değeri:  23.207788540194304


In [50]:
#8. Bir Numpy dizisindeki standart sapmayı bulun
print("Dizimiz: ",d)
print()
print("Dizinin Standart Sapma Değeri: ", d.std())

Dizimiz:  [  96.16774526  -15.21650631   22.70135604  113.55202944  -69.62850452
  -16.97413795  -93.43450606  -36.68228207  133.05145163 -228.24243699
  -51.86849265  128.85573756  125.13374129  186.82404409  -29.76394989
  132.69391175   49.17961312    1.74189147  -73.19387651   89.2589421 ]

Dizinin Standart Sapma Değeri:  100.30500109475899


In [ ]:
#9. Bir Numpy dizisinde tekrar eden elemanları bulun

In [11]:
e= np.random.randint(1,10,20)
uni = np.unique(e)

print(f"{e} dizisinin tekrar eden elemanları {uni}'dir")


[6 8 2 2 1 7 5 2 9 4 4 9 4 2 2 7 1 3 3 2] dizisinin tekrar eden elemanları [1 2 3 4 5 6 7 8 9]'dir


In [ ]:
#10. 2 boyutlu bir Numpy dizisindeki tüm elemanların toplamını bulun

In [15]:
summary = np.sum(b)
summary

71

In [17]:
#11. 2 boyutlu bir Numpy dizisindeki her bir satırdaki elemanların toplamını bulun
summary_satir=np.sum(b, axis=1)
summary_satir

array([24, 28, 19])

In [18]:
#12. 2 boyutlu bir Numpy dizisindeki her bir sütundaki elemanların toplamını bulun
summary_sutun=np.sum(b, axis=0)
summary_sutun

array([16, 37, 18])

In [42]:
#13. Numpy dizisi boyutlarını değiştirin

g = np.array(range(1,13))
print(g)

h=g.reshape(4,3)
print(h) 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
# ya da

g=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

g_reshaped = np.reshape(g, (4, 3))
print(g_reshaped)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#14. Numpy dizisindeki elemanların transpozunu alın

In [45]:
g_transpose = np.transpose(g)

In [58]:
#15. Numpy dizisindeki elemanların sıralamasını yapın
print("Dizimiz: ", d)
d_Sort=np.sort(d)
print()
print("Dizimizin sort komutuyla sıralanmış hali: ", d_Sort)

Dizimiz:  [  96.16774526  -15.21650631   22.70135604  113.55202944  -69.62850452
  -16.97413795  -93.43450606  -36.68228207  133.05145163 -228.24243699
  -51.86849265  128.85573756  125.13374129  186.82404409  -29.76394989
  132.69391175   49.17961312    1.74189147  -73.19387651   89.2589421 ]

Dizimizin sort komutuyla sıralanmış hali:  [-228.24243699  -93.43450606  -73.19387651  -69.62850452  -51.86849265
  -36.68228207  -29.76394989  -16.97413795  -15.21650631    1.74189147
   22.70135604   49.17961312   89.2589421    96.16774526  113.55202944
  125.13374129  128.85573756  132.69391175  133.05145163  186.82404409]


In [56]:
#16. 2 boyutlu bir Numpy dizisindeki her bir sütundaki elemanların ortalamasını bulun
## Yukarıda da yaptığım gibi, yine "b" olarak tanımlanmış iki boyutlu diziyi kullanacağım.

sutun_mean=np.mean(b, axis=0)
sutun_mean


array([ 5.33333333, 12.33333333,  6.        ])

In [57]:
#17. 2 boyutlu bir Numpy dizisindeki her bir satırdaki elemanların standart sapmasını bulun
sd_b = np.std(b, axis=1)
sd_b

array([7.11805217, 2.49443826, 4.78423336])

In [64]:
#18. 2 boyutlu bir Numpy dizisinde belirli bir elemanın index değerini bulun.
print(b)
index=np.where(b==13)
print(f" '13' elemanının index değeri = {index} ")



[[ 4 18  2]
 [10  6 12]
 [ 2 13  4]]
 '13' elemanının index değeri = (array([2]), array([1])) 


In [70]:
#19. 2 boyutlu bir Numpy dizisinde belirli bir sütunu seçin
print(b)
column= b[:,2]
print(f"dizinin üçüncü sütunu = {column}'dür")


[[ 4 18  2]
 [10  6 12]
 [ 2 13  4]]
dizinin üçüncü sütunu = [ 2 12  4]'dur


In [73]:
#20. 2 boyutlu bir Numpy dizisinde belirli bir satırı seçin
print(b)
row= b[2,:]
print(f"dizinin üçüncü satırı = {row}'dür")

[[ 4 18  2]
 [10  6 12]
 [ 2 13  4]]
dizinin üçüncü satırı = [ 2 13  4]'dür
